/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#a5c8ff",
        "error-container": "#ffdad6",
        "outline": "#717783",
        "surface-container": "#dbf1fe",
        "surface-variant": "#cfe6f2",
        "on-tertiary-fixed-variant": "#5c4300",
        "surface-bright": "#f3faff",
        "primary-fixed": "#d4e3ff",
        "tertiary-fixed": "#ffdfa0",
        "surface-container-highest": "#cfe6f2",
        "tertiary-fixed-dim": "#f8bd2a",
        "on-background": "#071e27",
        "secondary-fixed": "#98f994",
        "on-secondary-fixed": "#002204",
        "surface-container-high": "#d5ecf8",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c1c6d4",
        "surface": "#f3faff",
        "on-secondary-container": "#0c7521",
        "on-error-container": "#93000a",
        "tertiary-container": "#966f00",
        "on-primary-container": "#fffdff",
        "on-secondary-fixed-variant": "#005313",
        "surface-dim": "#c7dde9",
        "primary-container": "#1976d2",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#7ddc7a",
        "surface-container-low": "#e6f6ff",
        "on-primary-fixed": "#001c3a",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#dff4ff",
        "secondary": "#006e1c",
        "inverse-surface": "#1e333c",
        "surface-tint": "#005faf",
        "on-surface": "#071e27",
        "primary-fixed-dim": "#a5c8ff",
        "on-primary-fixed-variant": "#004786",
        "on-tertiary-fixed": "#261a00",
        "secondary-container": "#98f994",
        "on-primary": "#ffffff",
        "on-surface-variant": "#414752",
        "error": "#ba1a1a",
        "tertiary": "#775800",
        "on-error": "#ffffff",
        "primary": "#005dac",
        "on-tertiary-container": "#fffdff",
        "background": "#f3faff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
